version: '3.8'
services:
  chattts:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile-dev
      args:
        PROXY: http://192.168.50.48:7890
    volumes:
      # 这里需要替换为自己的实际映射路径
      - F:/Space/PRO/ai/ChatTTS:/app    
      - F:/.cache:/root/.cache    
    command: sleep infinity
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: 1
      # NVIDIA_VISIBLE_DEVICES: all
      XXXX_DEMO: XXXX_DEMO
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    # network_mode: host
    shm_size: 22g